# Tópicos Especiais em Banco de Dados - Manhã - 2023   
Professor: Vladimir Costa de Alencar   
Equipe:    
        MATEUS HENRIQUE SALES   
        FRANCISCO WELIO FIRMINO DA SILVA JUNIOR   
        ROMENILDO DO VALE FERREIRA   


## PROJETO PREDIÇÃO DE DIABETES
Projeto utilizando o data set: https://www.kaggle.com/datasets/mathchi/diabetes-data-set   
O objetivo é prever, com base em medidas diagnósticas, se um paciente tem diabetes.

## Importações

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
!pip install -q huggingface_hub

In [6]:
!pip install -q joblib

In [7]:
import pandas as pd
import numpy as np

In [8]:
url = "https://raw.githubusercontent.com/Romenildo/analise_de_dados/main/diabetes.csv"

## Data set dados

In [9]:
diabetesdf = pd.read_csv(url)
diabetesdf.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
df = diabetesdf.copy()
atributos = list(df.columns.values)
atributos.remove('Outcome')
print(atributos)


['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


In [11]:
# guardar os valores com seu valor minimo media e maximo
atributos_valores = {}
for atributo in atributos:
    minimo, media, maximo = df[atributo].min(), df[atributo].mean(), df[atributo].max()
    atributos_valores[atributo] = {"min": minimo, "media": media, "max": maximo }

atributos_valores

{'Pregnancies': {'min': 0, 'media': 3.8450520833333335, 'max': 17},
 'Glucose': {'min': 0, 'media': 120.89453125, 'max': 199},
 'BloodPressure': {'min': 0, 'media': 69.10546875, 'max': 122},
 'SkinThickness': {'min': 0, 'media': 20.536458333333332, 'max': 99},
 'Insulin': {'min': 0, 'media': 79.79947916666667, 'max': 846},
 'BMI': {'min': 0.0, 'media': 31.992578124999998, 'max': 67.1},
 'DiabetesPedigreeFunction': {'min': 0.078,
  'media': 0.47187630208333325,
  'max': 2.42},
 'Age': {'min': 21, 'media': 33.240885416666664, 'max': 81}}

In [14]:
diabetesdf.to_csv('diabetesData.csv', index=False)
!dir -ilah *.csv

 Volume in drive C has no label.
 Volume Serial Number is 0E46-61B6

 Directory of C:\Users\romen\Desktop\diabetes


 Directory of C:\Users\romen\Desktop\diabetes

11/29/2023  06:44 PM            24,059 diabetesData.csv
               1 File(s)         24,059 bytes
               0 Dir(s)  35,808,210,944 bytes free


In [15]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [16]:
df.Outcome.unique()

array([1, 0], dtype=int64)

In [17]:
df.Outcome.nunique()

2

In [18]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

## Criando o x e y

In [19]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [20]:
y = diabetesdf["Outcome"]
X = diabetesdf.drop(["Outcome"], axis=1)

X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [21]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [22]:
set(y)

{0, 1}

## Criando o modelo

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=65)

x_train.shape, x_test.shape

((614, 8), (154, 8))

## Criando o xgBoost

In [24]:
!pip install -q xgboost
import xgboost as xgb

In [25]:
set(y_train)

{0, 1}

### Treinando com as entrada

In [26]:
import numpy as np

In [27]:
labels = [0, 1]
labels_XGBoost = [0, 1]

In [28]:
for classe_XGBoost in labels_XGBoost:
    print('classe XGBoost: ' + str(classe_XGBoost) + ' - Classe Diabetes: '  +  \
           str(classe_XGBoost))

classe XGBoost: 0 - Classe Diabetes: 0
classe XGBoost: 1 - Classe Diabetes: 1


In [29]:
for classe in labels:
    print('classe Diabetes: ' + str(classe) + ' - Classe XGBoost: '  +  \
           str(classe))

classe Diabetes: 0 - Classe XGBoost: 0
classe Diabetes: 1 - Classe XGBoost: 1


## Preparando os dados

In [30]:
y = list()

for classe in list(y_train.values):

    y_train_XGBoost = classe
    y.append(y_train_XGBoost)
    
print(y[0:5])

[1, 0, 1, 0, 0]


In [31]:
set(y)

{0, 1}

## Treinando o modelo

In [32]:
%%time
learning_rate = 1.1   
xgb_classifier = xgb.XGBClassifier(eta = learning_rate , n_estimators=200)
xgb_classifier.fit(x_train.values, y)
xgb_classifier

CPU times: total: 297 ms
Wall time: 76.4 ms


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=1.1, eval_metric=None,
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [33]:
xgb_classifier

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=1.1, eval_metric=None,
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [34]:
labels = xgb_classifier.predict(X[:3])
labels

array([1, 0, 1])

## dados do modelo


In [35]:
modelo = xgb_classifier

In [36]:
modelo.get_params()

{'objective': 'binary:logistic',
 'base_score': None,
 'booster': None,
 'callbacks': None,
 'colsample_bylevel': None,
 'colsample_bynode': None,
 'colsample_bytree': None,
 'device': None,
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'feature_types': None,
 'gamma': None,
 'grow_policy': None,
 'importance_type': None,
 'interaction_constraints': None,
 'learning_rate': None,
 'max_bin': None,
 'max_cat_threshold': None,
 'max_cat_to_onehot': None,
 'max_delta_step': None,
 'max_depth': None,
 'max_leaves': None,
 'min_child_weight': None,
 'missing': nan,
 'monotone_constraints': None,
 'multi_strategy': None,
 'n_estimators': 200,
 'n_jobs': None,
 'num_parallel_tree': None,
 'random_state': None,
 'reg_alpha': None,
 'reg_lambda': None,
 'sampling_method': None,
 'scale_pos_weight': None,
 'subsample': None,
 'tree_method': None,
 'validate_parameters': None,
 'verbosity': None,
 'eta': 1.1}

In [37]:
modelo.get_metadata_routing()

{'fit': {'sample_weight': None, 'base_margin': None, 'eval_set': None, 'eval_metric': None, 'early_stopping_rounds': None, 'verbose': None, 'xgb_model': None, 'sample_weight_eval_set': None, 'base_margin_eval_set': None, 'feature_weights': None, 'callbacks': None}, 'predict': {'output_margin': None, 'validate_features': None, 'base_margin': None, 'iteration_range': None}, 'predict_proba': {'validate_features': None, 'base_margin': None, 'iteration_range': None}, 'score': {'sample_weight': None}}

In [38]:
dir(modelo)

['_Booster',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_is_fitted__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_can_use_inplace_predict',
 '_check_feature_names',
 '_check_n_features',
 '_configure_fit',
 '_create_dmatrix',
 '_estimator_type',
 '_get_default_requests',
 '_get_iteration_range',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_get_type',
 '_load_model_attributes',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_evaluation_result',
 '_validate_data',
 '_validate_params',
 'apply',
 'base_score',
 'best_iteration',
 'best_scor

In [39]:
modelo.classes_

array([0, 1])

## atributos mais importantes

In [40]:
modelo.feature_importances_

array([0.09482697, 0.27241215, 0.11853572, 0.08611634, 0.09130329,
       0.14485538, 0.07438246, 0.11756769], dtype=float32)

In [41]:
atributos = list(X.columns.values)
print(atributos)

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


In [42]:
dfi = pd.DataFrame( {'atributos' : atributos, 'importancia':  modelo.feature_importances_ })
dfi

atributos  importancia
0               Pregnancies     0.094827
1                   Glucose     0.272412
2             BloodPressure     0.118536
3             SkinThickness     0.086116
4                   Insulin     0.091303
5                       BMI     0.144855
6  DiabetesPedigreeFunction     0.074382
7                       Age     0.117568

In [43]:
dfo = dfi.sort_values(by='importancia', ascending=False).reset_index(drop=True)
dfo

atributos  importancia
0                   Glucose     0.272412
1                       BMI     0.144855
2             BloodPressure     0.118536
3                       Age     0.117568
4               Pregnancies     0.094827
5                   Insulin     0.091303
6             SkinThickness     0.086116
7  DiabetesPedigreeFunction     0.074382

In [44]:
atributos_importantes = dfo[:6]
atributos_importantes 

atributos  importancia
0        Glucose     0.272412
1            BMI     0.144855
2  BloodPressure     0.118536
3            Age     0.117568
4    Pregnancies     0.094827
5        Insulin     0.091303

In [45]:
atributos_mais_importantes = list(atributos_importantes.atributos)
atributos_mais_importantes 

['Glucose', 'BMI', 'BloodPressure', 'Age', 'Pregnancies', 'Insulin']

In [46]:
X.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23

In [47]:
X[ X.index == 233]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
233            4      122             68              0        0  35.0   

     DiabetesPedigreeFunction  Age  
233                     0.394   29

In [48]:
x1 = X[ X.index == 233].values
x1

array([[  4.   , 122.   ,  68.   ,   0.   ,   0.   ,  35.   ,   0.394,
         29.   ]])

In [49]:
import numpy as np

In [50]:
x1_XGBoost = modelo.predict(x1)
x1_XGBoost

array([0])

In [51]:
list(x1_XGBoost)

[0]

## deploy

In [52]:
import pickle as pkl

filehandler = open("ModeloXGBoost.pkl" ,"wb")
pkl.dump(modelo,filehandler)
filehandler.close()

!dir -lah *.pkl

 Volume in drive C has no label.
 Volume Serial Number is 0E46-61B6

 Directory of C:\Users\romen\Desktop\diabetes


 Directory of C:\Users\romen\Desktop\diabetes

11/29/2023  06:44 PM           214,892 ModeloXGBoost.pkl
               1 File(s)        214,892 bytes
               0 Dir(s)  35,807,940,608 bytes free


### Carregar o Modelo

In [53]:
file = "ModeloXGBoost.pkl"
with open(file, 'rb') as f:
    modelo_lido = pkl.load(f)
    
modelo_lido

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=1.1, eval_metric=None,
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [54]:
list(x1_XGBoost)[0]

0

In [55]:
!dir -ilha *.pkl

 Volume in drive C has no label.
 Volume Serial Number is 0E46-61B6

 Directory of C:\Users\romen\Desktop\diabetes


 Directory of C:\Users\romen\Desktop\diabetes

11/29/2023  06:44 PM           214,892 ModeloXGBoost.pkl
               1 File(s)        214,892 bytes
               0 Dir(s)  35,807,875,072 bytes free


In [56]:
set(y)

{0, 1}

## Estatística Descritiva do atributos

In [177]:
df = X

In [178]:
atributos = list(df.columns.values)
dic_atributos_valores = {}
for atributo in atributos:
    min, media, max = df[atributo].min(), df[atributo].mean(), df[atributo].max()
    print('atributo:', atributo, ':  ', min, media, max)
    step = (max - min) / media
    print('step:', step)
    dic_atributos_valores[atributo] = {'min': min, 'media': media, 'max': max, 'step': step }

atributo: Pregnancies :   0 3.8450520833333335 17
step: 4.421266508635286
atributo: Glucose :   0 120.89453125 199
step: 1.6460628776374036
atributo: BloodPressure :   0 69.10546875 122
step: 1.7654174438980272
atributo: SkinThickness :   0 20.536458333333332 99
step: 4.8206949023586105
atributo: Insulin :   0 79.79947916666667 846
step: 10.601572953039845
atributo: BMI :   0.0 31.992578124999998 67.1
step: 2.0973614485781615
atributo: DiabetesPedigreeFunction :   0.078 0.47187630208333325 2.42
step: 4.96316511267905
atributo: Age :   21 33.240885416666664 81
step: 1.8050060715264995


In [179]:
dic_atributos_valores

{'Pregnancies': {'min': 0,
  'media': 3.8450520833333335,
  'max': 17,
  'step': 4.421266508635286},
 'Glucose': {'min': 0,
  'media': 120.89453125,
  'max': 199,
  'step': 1.6460628776374036},
 'BloodPressure': {'min': 0,
  'media': 69.10546875,
  'max': 122,
  'step': 1.7654174438980272},
 'SkinThickness': {'min': 0,
  'media': 20.536458333333332,
  'max': 99,
  'step': 4.8206949023586105},
 'Insulin': {'min': 0,
  'media': 79.79947916666667,
  'max': 846,
  'step': 10.601572953039845},
 'BMI': {'min': 0.0,
  'media': 31.992578124999998,
  'max': 67.1,
  'step': 2.0973614485781615},
 'DiabetesPedigreeFunction': {'min': 0.078,
  'media': 0.47187630208333325,
  'max': 2.42,
  'step': 4.96316511267905},
 'Age': {'min': 21,
  'media': 33.240885416666664,
  'max': 81,
  'step': 1.8050060715264995}}

In [180]:
print(atributos) 

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


## Treino de acurácia e matriz de confusão

In [181]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred_XGBoost = xgb_classifier.predict(x_test)

y_test_modelo = list()
for classe in list(y_test.values):
    y_train_XGBoost = classe
    y_test_modelo.append(y_train_XGBoost)

acc_XGBoost = accuracy_score(y_test_modelo, y_pred_XGBoost)
print('Acurácia do modelo XGBoost:', acc_XGBoost)
cm = confusion_matrix(y_test_modelo, y_pred_XGBoost)
print('Matriz de Confusão - XGBoost:\n',cm)

print('============================================')

Acurácia do modelo XGBoost: 0.7012987012987013
Matriz de Confusão - XGBoost:
 [[79 18]
 [28 29]]


In [182]:
labels = xgb_classifier.predict(X[:3])
labels

array([1, 0, 1])

In [183]:
modelo = xgb_classifier
modelo.get_params()

{'objective': 'binary:logistic',
 'base_score': None,
 'booster': None,
 'callbacks': None,
 'colsample_bylevel': None,
 'colsample_bynode': None,
 'colsample_bytree': None,
 'device': None,
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'feature_types': None,
 'gamma': None,
 'grow_policy': None,
 'importance_type': None,
 'interaction_constraints': None,
 'learning_rate': None,
 'max_bin': None,
 'max_cat_threshold': None,
 'max_cat_to_onehot': None,
 'max_delta_step': None,
 'max_depth': None,
 'max_leaves': None,
 'min_child_weight': None,
 'missing': nan,
 'monotone_constraints': None,
 'multi_strategy': None,
 'n_estimators': 200,
 'n_jobs': None,
 'num_parallel_tree': None,
 'random_state': None,
 'reg_alpha': None,
 'reg_lambda': None,
 'sampling_method': None,
 'scale_pos_weight': None,
 'subsample': None,
 'tree_method': None,
 'validate_parameters': None,
 'verbosity': None,
 'eta': 1.1}

In [184]:
modelo.get_metadata_routing()

{'fit': {'sample_weight': None, 'base_margin': None, 'eval_set': None, 'eval_metric': None, 'early_stopping_rounds': None, 'verbose': None, 'xgb_model': None, 'sample_weight_eval_set': None, 'base_margin_eval_set': None, 'feature_weights': None, 'callbacks': None}, 'predict': {'output_margin': None, 'validate_features': None, 'base_margin': None, 'iteration_range': None}, 'predict_proba': {'validate_features': None, 'base_margin': None, 'iteration_range': None}, 'score': {'sample_weight': None}}

In [185]:
dir(modelo)

['_Booster',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_is_fitted__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_can_use_inplace_predict',
 '_check_feature_names',
 '_check_n_features',
 '_configure_fit',
 '_create_dmatrix',
 '_estimator_type',
 '_get_default_requests',
 '_get_iteration_range',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_get_type',
 '_load_model_attributes',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_evaluation_result',
 '_validate_data',
 '_validate_params',
 'apply',
 'base_score',
 'best_iteration',
 'best_scor

In [186]:
modelo.classes_

array([0, 1])